@ItemSearchAPI_HostAddress = http://localhost:5189

### Get all items
GET {{ItemSearchAPI_HostAddress}}/api/items
Accept: application/json

###

### Search item by barcode
GET {{ItemSearchAPI_HostAddress}}/api/items/search/barcode/1234567890123
Accept: application/json

###

### Search items by name
GET {{ItemSearchAPI_HostAddress}}/api/items/search/name/laptop
Accept: application/json

###

